global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Backend API
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Frontend (nginx metrics if available)
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 30s

  # CV Service
  - job_name: "cv-service"
    static_configs:
      - targets: ["cv-mock:9000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Docker containers
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s
