global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # ReBin Pro Backend API
  - job_name: "rebin-api"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # ReBin Pro Frontend
  - job_name: "rebin-frontend"
    static_configs:
      - targets: ["frontend:80"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Supabase Database
  - job_name: "supabase-db"
    static_configs:
      - targets: ["supabase-db:5432"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Cloudflare Worker (via custom metrics endpoint)
  - job_name: "cloudflare-worker"
    static_configs:
      - targets: ["worker-metrics:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
